publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "http://blachlylab.org/"
canonifyurls = true
theme = "hugo-academic-group"
title = "Blachly Lab"
math = true
copyright = "&copy; Blachly Lab, 2022"

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Website of research group"
  author = "James Blachly"
  email = "james.blachly@osumc.edu"
  address = '<a href="https://www.google.com/maps?q=460+W+10th+Ave,+Columbus,+OH+43210&um=1&ie=UTF-8&sa=X&ved=2ahUKEwiTzeWW6bL1AhXPLc0KHeUzBycQ_AUoAXoECAEQAw">460 W 10th Ave, Columbus, OH 43210, United States</a>'
  slogan = "BLACHLY LAB"
  slogan_icon = "img/lab_logo.png"
  slogan_text = "Leverage emerging genome technologies to advance the understanding and treatment of leukemia"

 [params.logo]
    image = "img/lab_logo.png"

  [[params.navbar_hierarchy]]
    name = "Blachly Lab"
    position = 1
  
  [[params.sponsors]]
    name = "OSTOR"
    link = "https://cancer.osu.edu/for-cancer-researchers/resources-for-cancer-researchers/orien"
    image = "/img/ORIEN_Logo.png"
  [[params.sponsors]]
    name = "ASTOR"
    link = "https://www.allianceforclinicaltrialsinoncology.org/main/public/standard.xhtml?path=%2FPublic%2FFoundation"
    image = "/img/Alliance_Foundation_Logo.png"
  [[params.sponsors]]
    name = "HCLF"
    link = "https://www.hairycellleukemia.org/"
    image = "/img/HCLF.png"
  [[params.sponsors]]
    name = "SASS"
    link = "https://sassfoundation.org/"
    image = "/img/SASS.png"
  [[params.sponsors]]
    name = "NCCN"
    link = "https://www.nccn.org/"
    image = "/img/NCCN.png"
  [[params.sponsors]]
    name = "PELO"
    link = "https://www.pelotonia.org/"
    image = "/img/pelotonia.png"
  [[params.sponsors]]
    name = "OSUSC"
    link = "https://www.osc.edu/"
    image = "/img/OSUSC.png"
  [[params.sponsors]]
    name = "SR"
    link = "https://www.storagereview.com/"
    image = "/img/Storage-Reviews.png"
  
  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  [[params.slogan_columns]]
    title = "About"
    text =  "We pride ourselves on using the most cutting edge technologies to aid in research of leukemia. Our hope is the research we do directly impacts the understanding and treatment of leukemia, generating better outcomes for patients in the future. Checkout more about our tools on our GitHub or checkout what the lab has been up to in our Blog."
    link = "/about"
    link_text = "Meet the team"
    weight = 1
  
  [[params.slogan_columns]]
    title = "Mission"
    text = "The Blachly Lab’s mission is to advance research in understanding the role genetics and genomics play in the development, progression and treatment of blood cancers — especially acute myeloid leukemia (AML) and chronic lymphocytic leukemia (CLL) — and return that information back to the clinic, informing the design of future clinical trials to improve patient care."
    link = "/mission"
    link_text = "Read more"
    weight = 2

  [[params.slogan_columns]]
    title = "Approach"
    text = "Members of the lab  collaborate broadly with other scientists to help use bioinformatics and computational biology to answer important questions about cancer - a majority of this collaborative work also focused in leukemia. Software developed in the lab is broadly applicable in cancer research aiding in the lab's own leukemia-focused work; we use our tools and those of the scientific community to examine functional genomic biomarkers from clinical trials to help inform contemporary treatment and guide the development of future therapeutics."
    link = "/approach"
    link_text = "Read more"
    weight = 3

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 3
    str_all = "More Projects"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Vacancies"
    subtitle = ""
    count = 3
    str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 1

  [[menu.main]]
      name = "Research"
      url = "/research"
      weight = 2

  [[menu.main]]
      name = "Publications"
      url = "/#publications"
      weight = 3

    [[menu.main]]
      name = "Projects"
      url = "/#projects"
      weight = 4

  [[menu.main]]
      name = "Members"
      url = "/#members"
      weight = 5

  [[menu.main]]
      name = "Blog"
      url = "/#posts"
      weight = 6

  [[menu.main]]
    name = "Software"
    weight = 7
    identifier = "software"
  [[menu.main]]
    name = "dhtslib"
    url = "https://github.com/blachlylab/dhtslib"
    parent = "software"
    weight = 1
  [[menu.main]]
    name = "nopilesum"
    url = "https://github.com/blachlylab/nopilesum"
    parent = "software"
    weight = 1
  [[menu.main]]
    name = "recontig"
    url = "https://github.com/blachlylab/recontig"
    parent = "software"
    weight = 1
  [[menu.main]]
    name = "fade"
    url = "https://github.com/blachlylab/fade"
    parent = "software"
    weight = 1
  [[menu.main]]
    name = "mucor3"
    url = "https://github.com/blachlylab/mucor3"
    parent = "software"
    weight = 1
  [[menu.main]]
    name = "fishnet"
    url = "https://github.com/blachlylab/fishnet"
    parent = "software"
    weight = 1
  [[menu.main]]
    name = "maskerade"
    url = "https://github.com/blachlylab/maskerade"
    parent = "software"
    weight = 1
  [[menu.main]]
    name = "SABER"
    url = "https://github.com/blachlylab/SABER"
    parent = "software"
    weight = 1
  [[menu.main]]
    name = "swiftover"
    url = "https://github.com/blachlylab/swiftover"
    parent = "software"
    weight = 1

  [[menu.main]]
    name = "Join us"
    weight = 7
    identifier = "Join us"
  [[menu.main]]
    name = "Vacancies"
    parent = "Join us"
    weight = 1
  [[menu.main]]
    name = "Internships"
    parent = "Join us"
    weight = 1

  [[menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 8